a=['a','b','c','d','f','g','h',]
b=['a','b','c','d','f','g','h',]
c=['a','b','c','d','f','g','h',]
d=['a','b','c','d','f','g','h',]
f=['a','b','c','d','f','g','h',]
g=['a','b','c','d','f','g','h',]
h=['a','b','c','d','f','g','h',]
i=['a','b','c','d','f','g','h',]
j=['a','b','c','d','f','g','h',]
k=['a','b','c','d','f','g','h',]
l=['a','b','c','d','f','g','h',]

print(a.insert)
print(b.append)
print(c.clear)
print(d.copy)
print(f.count)
print(g.extend)
print(h.index)
print(i.pop)
print(j.remove)
print(k.reverse)
print(l.sort)